[gcp_service_account]
type = "service_account"
project_id = "composed-setup-453515-u4"
private_key_id = "4a7deeeb33221f58d404bd897fd3ca6e127105c1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3ENyA3VIV0y4j
aMCEHjSB16OQIWwaju6v19npVmcTgiIGuZ6HJexUq8tktW3kabFp7AxvWTBwpZzM
RAPSNfN1EISzddAukXGqmcvuCDemrAq4LAAr07QEK+geMjFRKW15vYrpomum5eij
4gyhYM0TlT4u63bJ5Uk9mUbNf3DA6GSed223duLFB33HhlsVLfPmK0ImQvjfVxlz
WcchZM+IYyJXN3fcbx9JqZLUc413LcBSGWhdHWxsSfLzCENLQrjZXvM0qfdwUseR
47yJ2mj3gg2DF9jGWXoV66s7ZFCIUW5v3tUf7RPQF+jqErXD0kWx6SVIRKZoWvNz
syRkl4MdAgMBAAECggEAPLmzo22HGqVEQ0uuvMS2PzH0WE216fNq2tq7tsrKA28h
8WAmZYdfZ1Dbdcs3KlMjHlNGZrNLvbo6EoonSFZMLZNuqYcVqTTm4yQEQS/pofik
z6YM4nzl1JJp+4ZD1LvszDrjNxABLMpMCvzjmq6dKHdTusWx0FQmIPBUy7sQAHUm
lqUq5DxaPzphjRkzX1HWsvo6uSNBKwOUoTX3xZkd2g3E47D+K75iR8ikgTBmi8ay
K/9U2ligNO2zuADI87jaJdfmv07dpRj736H5+tF9qzPawfB2YeLrEfPXQLhqHfDm
uWoQuHUl0oT73fQdr+qK6VWGt/xCo1zIS+1tnHRqkwKBgQDh5lE4RAgV5PCuCdSu
OWYTLi29ciVfouW9oAc8iGbXknDGznZXvByW0l4M8eefd7jC0m4MFmPFEfdYB7+O
DLCaE7jtx22AzjF/Adad0/EcD4p6ZtiOn7UmXpTd84u9jH4WlFVz3TCAforFPT2Q
lyZQbCXU+pKcQxP5aNa1pgP5MwKBgQDPdW+zfQn7Y4jzdo8yLxMMZDTSMJ2TCfN9
yhJGccSoB82kKvSlb/MgEM+mY1z6D2MFXlmGu1jbJGP9ifsEhmBDU+ZMX5k1zVV6
4pz3Rp5cABtxt3Md9ssU6VWTJI7Oe40y3bY1dFZ83bQKw5/2y43R6UbLtrfa/Owq
cEECXgOybwKBgGQldRBaqLL8Ie8mEJGEhMowCLsZ5ZO2Zd9hGJQvbFhZZYHdef1/
ObVrYaKfg63gp5pHK95T9rshMeRm2vcgjRJhd/SCGvulba/+oqSplxR3l06YVZ01
FFwERj73f5XyuNtNu2x4PM5aSy8R7T8yoxu4NjVrOJ/p5OsHHVi+VridAoGAC79L
nu9CpHCDbb3V5/KQcpAuCYTlN1FF72aE2GZSy2z9sQEZr1CChNtO1s4jkqlSYxhv
m1h6dJY/7zhj9WKiis1yafqz0z8YSwgP+VSPXQhIhYzswNKbt0hrJxTX3UtTuICj
c61txE5NhpqDMVdfZXZ/IsPq70SJHvISTE8EiJMCgYEAww1ccoFs1yy+Cf1DCIIZ
qdnhrB9a1uoXG3ray6lSklPmGfICuWJK8iePNK30oSm01BlXqxCPgKsc6/CIeoDR
9+1ICnd2uvxcJryoAdOnPTqehDVPa8nmHgT/BdMWorCMFpvflUfd9crmxEXg1G4X
tOg16243YwhmC0KesGhzcrY=
-----END PRIVATE KEY-----"""
client_email = "python-api@composed-setup-453515-u4.iam.gserviceaccount.com"
client_id = "118381075002793756056"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/python-api%40composed-setup-453515-u4.iam.gserviceaccount.com"
