[gcp_service_account]
type = "service_account"
project_id = "composed-setup-453515-u4"
private_key_id = "edff0c63061a9df9419cba4ddc63d3c859d0b6ae"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMAWKcT7GgUTBb
CCFZNbYQhn0Ya/yFHmhAUytyE/KwvUUzglEUM+nzGcIX4kH6Z8nnEuYffyQk8Bf2
si15LYlcmeTRlDKlH69XR7KDlYNScZHg3CsDkxguZn4RPDgPQzWDuPbHQ362XPvy
RbnWxkbIpinbrv/0/gG2HQjK19rr6VmlzT/hUGaUPihYsl5jklaOYj/XNZA/SWmS
2Z7+QzSshvg6TaPC+uAcNckYPR6tB5Omie1EpOwStItYIxIi4ju1wYbNigVhtZGn
ZD9ynC1oNW03n+KVqYTvdqvqF0EkP9Ze95SsRvLCGbWI8URrl4OlRDL0SHpkmV2O
IePB/ZJrAgMBAAECggEAH5hfU2IsWm34lUCvGYfuCKUrnqqq01sgPkYjRmm8fo7x
tsaKFBzuMM5edyB9o3CLnpQYu+wPBwGAVJ7H2CqrSYI0JBlVtqkvmM7r4OE5E32v
YCn5J3aSmi0ZfUXcUNDR6vKslbPoXgoMozsVSyQuNkk11mZGEgV88l2QzQmdSEf2
1BKZt4AiymooeUNpIrQNPwGhs+UUZJmkDV/xlnDUcL4EPxtOt0Hfduv4puZUiyHd
X74FpIXQfjqXbNWE7BGwhhA2gD3nF19uin67dUmp1wb8/2G0uIiIOO7xrZQq/Lkw
aXWmMY+8SUpe3QX3k3JjjJntxopVzdiL0N7Jf8FAwQKBgQDvKQKXW/qAwAx3Hogm
s3Mqj5WoJUXAL9eI+FoZnVdoNplzFpZG6kD0goKGL8lT1ltDq7W601QRX4YYncBS
cWpXOslZLYXRPLNZr/cVk+q6RWVVorP5qdbeuagjVMwKTjuW1eduNKF3AvwnHSOn
nw9QbFu+JLiRrBtunaJ9Nbz6UQKBgQDaXrD86PcBqOPJDRJMHVokM0ngPpqBekhy
aNyqZPIuyRjtRtYJZieQ4hnF4y5yX95j0F7uiDsWbHuinQD+6L0i4o+/CrGlDhgc
+y10bLad8emQvMEHyVaj9CaKsEjuEv+HP95FQfn61oEtlc0xnyJHhqeGtNMKXKAx
Y1eKgBOV+wKBgAkCjYNwRqa1FYMjVlPG7O7MjAHSracI5mDVomdWoyVc8TkBv9Wa
G6pahFpT0IzlBXkuLeGE9qTU6XNh9g3lEfGJWG6QpXr1g3g8hd19PhmYZbHtOESO
nnaznd7+4dT9j4cmNdrUBsU6Co/arC4zcts/ydEHByENz9bB/44iCSWRAoGATrO6
DizYeVypXBi983jQuCNUCOIHRYsQ+UsZ3L+tGXeY6EuTcKfEss8KguuyHb63pDnB
PS8UPKy0kpMLfNPc9um47R2pkNdXkXplk4Rq/NnnWCbvWyMRet3P1kRaxJNMTS6T
qVpyAhm1TPyki7HS5Px+/GnHdgCUK7imIGCwrmkCgYEAuTwK8DxxOzZYOaaS2hHp
imLA2Z8fD/APSmqe3yha3tALHIsGxWsDm47/GRezdaYM5x7JacgHB6EqybUelG/Q
+zPkh7VJ6CHBUYELQBqtGELqjSpfCgdOKWTEQU+huVCwlXvUZt1G6d+3V40CLIYv
17Toqt1bNW/YxfY8h7wNwvs=
-----END PRIVATE KEY-----"""
client_email = "python-api@composed-setup-453515-u4.iam.gserviceaccount.com"
client_id = "118381075002793756056"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/python-api%40composed-setup-453515-u4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
